service: lili
app: lili
org: carlosphilipe

provider:
  name: aws
  runtime: nodejs10.x
  region: sa-east-1
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::*"

functions:
  hello:
    environment:
      bucket: lili
    handler: handler.hello
    events:
      - http:
          path: post/image
          method: post
